name: Deploy To Heroku

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy to heroku
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: what branch is this?
      run: git branch

    - name: heroku login
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        args: container:login

    - name: heroku push
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        api_key: ${{ secrets.api_key }}
        client_id: ${{ secrets.client_id }}
        client_secret: ${{ secrets.client_secret }}
        project_id: ${{ secrets.project_id }}
        spreadsheet_id: ${{ secrets.spreadsheet_id }}
        spreadsheet_range: ${{ secrets.spreadsheet_range }}
      with:
        args: container:push -a brainwriting web --arg api_key,client_id,client_secret,project_id,spreadsheet_id,spreadsheet_range

    - name: heroku release
      uses: actions/heroku@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      with:
        # heroku has 2 process types: web and worker
        # web sleeps after 30 on free tier
        # worker keeps on chugging along (using up your 500-1000 free "dyno" hours 24/7
        # https://devcenter.heroku.com/articles/free-dyno-hours#dyno-sleeping
        # https://devcenter.heroku.com/articles/process-model#basics
        args: container:release -a brainwriting worker
